export const TROPTIX_FEE_FLAT = 'TROPTIX_FEE_FLAT';
export const TROPTIX_FEE_PERCENTAGE = 'TROPTIX_FEE_PERCENTAGE';
export const TROPTIX_FEE_TAX = 'TROPTIX_FEE_TAX';
export const TROPTIX_ORGANIZER_ALLOW_LIST = 'TROPTIX_ORGANIZER_ALLOW_LIST';
